<a href="https://colab.research.google.com/github/sherjahong1r/my-data-sayns-lessons/blob/main/2_Lug'atdan_Series_yaratish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from pandas import Series

In [6]:
obj2=Series([6, 3, 4, 5, 1], index=['a', 'b', 'c', 'd', 'e']) # bu orqali Indexlarni o'zimiz yaratamiz

In [7]:
print(obj2)

a    6
b    3
c    4
d    5
e    1
dtype: int64

In [8]:
np.exp(obj2)

a    403.428793
b     20.085537
c     54.598150
d    148.413159
e      2.718282
dtype: float64

In [9]:
obj2

a    6
b    3
c    4
d    5
e    1
dtype: int64

In [10]:
cars_dict = {'Malibu':40000, 'Lacetti':20000, 'Toyota':45000, 'Mazda':52000, 'Honda':38000}

In [11]:
type(cars_dict)

dict

In [23]:
cars1 = Series(cars_dict)

In [22]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [ ]:
type(cars1)

In [27]:
cars1 = Series({'Malibu':40000, 'Lacetti':20000, 'Toyota':45000, 'Mazda':52000, 'Honda':38000})

In [28]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [29]:
'Malibu' in cars1

True

In [30]:
"Nexia" in cars1

False

In [31]:
cars1['Toyota']

np.int64(45000)

In [32]:
cars_dict

{'Malibu': 40000,
 'Lacetti': 20000,
 'Toyota': 45000,
 'Mazda': 52000,
 'Honda': 38000}

In [33]:
models = ['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota', 'BMW', 'Mercedes'] # Yuqoridagi cars1 ichiga yangi modellar qo'shilib ro'yxat yaratildi

In [34]:
cars2 = Series(cars_dict, index=models) # Hamda index ni models bo'yicha o'qi va yangi mashinalar narxi bo'lmagani uchun o'rnini non qiladi

In [35]:
cars2

Honda       38000.0
Mazda       52000.0
Lacetti     20000.0
Jaguar          NaN
Malibu      40000.0
Toyota      45000.0
BMW             NaN
Mercedes        NaN
dtype: float64